server:
  port: 7002
spring:
  application:
    name: uk-warehouse
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    active: dev
    group:
      dev: dev-jdbc,dev-seata
      prod: prod-jdbc,prod-seata
