server:
  port: 7003
spring:
  application:
    name: uk-acct
  datasource:
    username: uk
    password: 123456
    host: localhost
    port: 3307
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/seata_uk?serverTimezone=Asia/Shanghai
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    active: seata
  jpa:
    hibernate:
      ddl-auto: update