server:
  port: 7002
spring:
  application:
    name: uk-warehouse
  cloud:
#    consul:
#      discovery:
#        instance-id: ${spring.application.name}
#        health-check-interval: 5s
#        health-check-path: /my-health-check
#      host: localhost
#      port: 8500
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848
  profiles:
    active: dev
    group:
      dev: dev-jdbc,dev-seata
      prod: prod-jdbc,prod-seata
