spring:
  datasource:
    host: localhost
    port: 3306
    dynamic:
      druid:
        # 初始连接数
        initialSize: 5
        # 最小连接池数量
        minIdle: 10
        # 最大连接池数量
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        # 配置一个连接在池中最大生存的时间，单位是毫秒
        maxEvictableIdleTimeMillis: 900000
        # 配置检测连接是否有效
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
      primary: master # 设置默认的数据源或者数据源组,默认值即为master。当有多个master_{}时会随机master。也可以指定固定的某个master
      strict: false # 严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master_1:
          url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/seata_uk?serverTimezone=Asia/Shanghai
          username: uk
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        master_2:
          url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/seata_uk2?serverTimezone=Asia/Shanghai
          username: uk
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/seata_uk_s1?serverTimezone=Asia/Shanghai
          username: uk
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_2:
          url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/seata_uk_s2?serverTimezone=Asia/Shanghai
          username: uk
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
      # 自定义负载均衡策略。slave组下有；多个个数据源，当用户使用 slave 切换数据源时会使用负载均衡算法。系统自带了两个负载均衡算法 LoadBalanceDynamicDataSourceStrategy 轮询,是默认的。 RandomDynamicDataSourceStrategy 随机的。
      strategy: com.baomidou.dynamic.datasource.strategy.LoadBalanceDynamicDataSourceStrategy
      seata: true
      seata-mode: at