server:
  port: 7002
spring:
  application:
    name: uk-warehouse
  datasource:
    username: uk
    password: 123456
    url: jdbc:mysql://localhost:3307/seata_uk?serverTimezone=Asia/Shanghai
  cloud:
#    consul:
#      discovery:
#        instance-id: ${spring.application.name}
#        health-check-interval: 5s
#        health-check-path: /my-health-check
#      host: localhost
#      port: 8500
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848
  jpa:
    hibernate:
      ddl-auto: update
