server:
  port: 7001
spring:
  application:
    name: uk-order
  datasource:
    username: uk
    password: 123456
    url: jdbc:mysql://localhost:3306/seata_uk?serverTimezone=Asia/Shanghai
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: seata

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000