seata:
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
  tx-service-group: default_tx_group
  registry:
    nacos:
      server-addr: localhost:8848
      application: seata-server
      group: SEATA_GROUP
  data-source-proxy-mode: XA